#!/usr/bin/bash

MYUSERNAME=AMOL
MYPASSWORD=1234
STARTOFSCRIPT=$(date)
ENDOFSCRIPT=$(date)

echo "USERNAME:" $MYUSERNAME
echo "PASSWORD:" $MYPASSWORD
echo "start-time:" $STARTOFSCRIPT
echo "End_time:" $ENDOFSCRIPT

